from pathlib import Path


SEÑAS = ["HOLA", "GRACIAS", "SI", "NO", "AYUDA"]
SEÑA_DESCONOCIDA = "OTRA"
SEÑAS_ENTRENAMIENTO = SEÑAS + [SEÑA_DESCONOCIDA]
ETIQUETA_DESCONOCIDA = "Señal no reconocida"

CARPETA_BASE = Path(__file__).resolve().parent
RUTA_DATOS = CARPETA_BASE / "data" / "sequences"
RUTA_MODELO = CARPETA_BASE / "models" / "sign_model.joblib"

LARGO_SECUENCIA = 30
MUESTRAS_OBJETIVO_POR_SEÑA = 20

CONFIANZA_MINIMA_DETECCION = 0.5
CONFIANZA_MINIMA_SEGUIMIENTO = 0.5
CONFIANZA_MINIMA_PREDICCION = 0.3
